#!/usr/bin/env python3
import argparse
import json
import os
from pathlib import Path
import sys
import urllib.error
import urllib.parse
import urllib.request

API_ROOT = "https://api.cloudflare.com/client/v4"
ACCOUNT_DB_NAME = "search_database_dev"
PLATFORM_DB_NAME = "mahayana-platform-development"


def api_request(method, path, token, payload=None):
    body = None
    headers = {
        "Authorization": f"Bearer {token}",
        "Accept": "application/json",
    }
    if payload is not None:
        body = json.dumps(payload).encode("utf-8")
        headers["Content-Type"] = "application/json"
    request = urllib.request.Request(
        f"{API_ROOT}{path}", data=body, headers=headers, method=method
    )
    try:
        with urllib.request.urlopen(request, timeout=30) as response:
            data = json.load(response)
    except urllib.error.HTTPError as exc:
        detail = exc.read().decode("utf-8", errors="replace")
        raise RuntimeError(
            f"Cloudflare API {method} {path} failed with HTTP {exc.code}: {detail}"
        ) from exc
    except urllib.error.URLError as exc:
        raise RuntimeError(f"Cloudflare API {method} {path} failed: {exc.reason}") from exc
    if not data.get("success"):
        raise RuntimeError(
            f"Cloudflare API {method} {path} returned errors: {data.get('errors')}"
        )
    return data


def list_d1_databases(account_id, token):
    databases = []
    page = 1
    while True:
        query = urllib.parse.urlencode({"page": page, "per_page": 100})
        data = api_request(
            "GET", f"/accounts/{account_id}/d1/database?{query}", token
        )
        databases.extend(data.get("result") or [])
        info = data.get("result_info") or {}
        total_pages = int(info.get("total_pages") or 1)
        if page >= total_pages:
            return databases
        page += 1


def find_database(databases, name):
    matches = [database for database in databases if database.get("name") == name]
    if len(matches) > 1:
        raise RuntimeError(f"multiple Cloudflare D1 databases are named {name!r}")
    return matches[0] if matches else None


def ensure_database(account_id, token, name):
    existing = find_database(list_d1_databases(account_id, token), name)
    if existing:
        database_id = existing.get("uuid")
        if not database_id:
            raise RuntimeError(f"D1 database {name!r} is missing a uuid")
        print(f"Resolved existing D1 database {name}: {database_id}")
        return database_id

    print(f"Creating isolated development D1 database {name}")
    try:
        data = api_request(
            "POST",
            f"/accounts/{account_id}/d1/database",
            token,
            {"name": name},
        )
        created = data.get("result") or {}
        database_id = created.get("uuid")
        if database_id:
            print(f"Created D1 database {name}: {database_id}")
            return database_id
    except RuntimeError:
        # A concurrent CD run may have created the database after our first list.
        existing = find_database(list_d1_databases(account_id, token), name)
        if existing and existing.get("uuid"):
            database_id = existing["uuid"]
            print(f"Resolved concurrently-created D1 database {name}: {database_id}")
            return database_id
        raise

    existing = find_database(list_d1_databases(account_id, token), name)
    if existing and existing.get("uuid"):
        return existing["uuid"]
    raise RuntimeError(f"Cloudflare created {name!r} but did not return a usable uuid")


def render_config(source_text, account_database_id, platform_database_id):
    if "YOUR_DEV_DATABASE_ID" in source_text:
        raise RuntimeError(
            "wrangler.toml still contains the retired YOUR_DEV_DATABASE_ID placeholder"
        )
    forbidden = (
        "[[env.development.d1_databases]]",
        "[[env.development.durable_objects.bindings]]",
    )
    for marker in forbidden:
        if marker in source_text:
            raise RuntimeError(
                f"base wrangler.toml must leave development runtime bindings to CD: {marker}"
            )

    insert_before = "[env.development.vars]"
    if insert_before not in source_text:
        raise RuntimeError("could not locate env.development vars block")

    generated = f'''# Development runtime bindings are generated by CD from Cloudflare resources.\n[[env.development.d1_databases]]\nbinding = "DB"\ndatabase_name = "{ACCOUNT_DB_NAME}"\ndatabase_id = "{account_database_id}"\nmigrations_dir = "migrations"\n\n[[env.development.d1_databases]]\nbinding = "PLATFORM_DB"\ndatabase_name = "{PLATFORM_DB_NAME}"\ndatabase_id = "{platform_database_id}"\nmigrations_dir = "../../third_party/mahayana/mahayana-rs/mahayana-platform-worker/migrations"\n\n[[env.development.durable_objects.bindings]]\nname = "ONLINE_COUNTER"\nclass_name = "OnlineCounter"\nscript_name = "fabushi-flutter-web-dev"\n\n'''
    return source_text.replace(insert_before, generated + insert_before, 1)


def self_test():
    source = '''[env.development]\nname = "fabushi-flutter-web-dev"\n\n[env.development.vars]\nENVIRONMENT = "development"\n'''
    rendered = render_config(
        source,
        "11111111-1111-1111-1111-111111111111",
        "22222222-2222-2222-2222-222222222222",
    )
    required = (
        'binding = "DB"',
        f'database_name = "{ACCOUNT_DB_NAME}"',
        'database_id = "11111111-1111-1111-1111-111111111111"',
        'binding = "PLATFORM_DB"',
        f'database_name = "{PLATFORM_DB_NAME}"',
        'database_id = "22222222-2222-2222-2222-222222222222"',
        '[[env.development.durable_objects.bindings]]',
        'script_name = "fabushi-flutter-web-dev"',
    )
    missing = [value for value in required if value not in rendered]
    if missing:
        raise RuntimeError(f"self-test missing rendered values: {missing}")
    print("development Wrangler config self-test passed")


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("source", nargs="?")
    parser.add_argument("output", nargs="?")
    parser.add_argument("--self-test", action="store_true")
    args = parser.parse_args()

    if args.self_test:
        self_test()
        return 0
    if not args.source or not args.output:
        parser.error("source and output are required unless --self-test is used")

    token = os.environ.get("CLOUDFLARE_API_TOKEN", "").strip()
    account_id = os.environ.get("CLOUDFLARE_ACCOUNT_ID", "").strip()
    if not token or not account_id:
        raise RuntimeError(
            "CLOUDFLARE_API_TOKEN and CLOUDFLARE_ACCOUNT_ID are required"
        )

    source_path = Path(args.source)
    output_path = Path(args.output)
    source_text = source_path.read_text(encoding="utf-8")
    account_database_id = ensure_database(account_id, token, ACCOUNT_DB_NAME)
    platform_database_id = ensure_database(account_id, token, PLATFORM_DB_NAME)
    output_path.write_text(
        render_config(source_text, account_database_id, platform_database_id),
        encoding="utf-8",
    )
    print(f"Prepared development Wrangler config: {output_path}")
    return 0


if __name__ == "__main__":
    try:
        raise SystemExit(main())
    except Exception as exc:
        print(f"prepare-development-wrangler: {exc}", file=sys.stderr)
        raise SystemExit(1)
