name: Post-main E2E Release delivery
on:
  workflow_dispatch:
jobs:
  paused:
    runs-on: ubuntu-latest
    steps:
      - run: echo 'Automatic post-main multi-platform delivery paused for 2026-09-05 Mac test release.'
